server:
  port: 8002
  tomcat:
    max-threads: 500
    min-spare-threads: 50

sharding:
  jdbc:
    datasource:
      names: ds_0,ds_1
      ds_0:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/demo_ds_0
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
        validationQuery: SELECT 1 FROM DUAL
        filters: stat,wall,log4j
      ds_1:
        type: com.alibaba.druid.pool.DruidDataSource
        url: jdbc:mysql://localhost:3306/demo_ds_1
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
        validationQuery: SELECT 1 FROM DUAL
        filters: stat,wall,log4j
    config:
      sharding:
        defaultDataSourceName: ds_0
        default-database-strategy:
          inline:
            sharding-column: user_id
            algorithm-expression: ds_${user_id % 2}
        tables:
          t_order:
            actual-data-nodes: ds_${0..1}.t_order
            key-generator-column-name: order_id
          t_order_item:
              actual-data-nodes: ds_${0..1}.t_order_item
              key-generator-column-name: order_item_id


        props:
          sql.show: true

mybatis:
  mapperLocations: classpath:mapping/**/*.xml