spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?characterEncoding=utf-8&verifyServerCertificate=false&useSSL=false&requireSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456

regCenter:
  serverList: localhost:2181
  namespace: elastic-job-lite-springboot

simpleJob:
  cron: 0/5 * * * * ?
  shardingTotalCount: 3
  shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou

#dataflowJob:
#  cron: 0/5 * * * * ?
#  shardingTotalCount: 3
#  shardingItemParameters: 0=Beijing,1=Shanghai,2=Guangzhou

